### ISSUE TITLE
telnet plugin systeminfo returns invalid json string for system time

### ISSUE THREAD

**Issue by pocki80** [OLSR/OONF#11]
The json string returned from telnet plugin "systeminfo" is not fully valid: the double-quotes for the value of key time_interval are missing.

**echo "systeminfo json time" | nc 127.0.0.1 2009**
```
{"time": [{
"time_system":"16:17:54.375",
"time_internal":608.432k}]}
```

Expected output:
```
{"time": [{
"time_system":"16:17:54.375",
"time_internal":"608.432k"}]}
```

**Comment by HRogge** [comment]
Fixed with commit 5840f6acf42f77274ef652e601c9e34974ae21cc
