### ISSUE TITLE
RPM packages

### ISSUE THREAD

**Issue by bitchecker** [OLSR/OONF#12]
hi,
there will be available a [script](https://github.com/OLSR/OONF/blob/master/files/create_debian_package.sh) or a [spec file](https://github.com/OLSR/olsrd/blob/master/redhat/olsrd.spec) for build it on rpm distros?

**Comment by fhuberts** [comment]
the v1 spec file probably is very out-of-date.
however, creating a spec file is rather easy...

**Comment by bitchecker** [comment]
> the v1 spec file probably is very out-of-date.
yes, is very out-of-date, in fact i was thinking of fork and add systemd support and create a pull request.

> however, creating a spec file is rather easy...
so, it will be added or i need to create from myself?

**Comment by bittorf** [comment]
@bitchecker - please create it, test it and send a pull request - so we can include it.

**Comment by fhuberts** [comment]
I have a local branch with work-in-progress on this, I'll push it out in a bit

**Comment by mathiashro** [comment]
@bitchecker / @fhuberts, I guess we are good to close this issue?
