### ISSUE TITLE
remotecontrol does not answer with default data

### ISSUE THREAD

**Issue by gabri94** [OLSR/OONF#13]
By making the request:
` config get olsrv2.tc_interval`
or 
`config get interface.hello_interval`
I expect to receive the value of the interval setted by the user in the configuration file, otherwise i expect to receive the default value.

Unfortunately the answer to that request is:
```
> config get olsrv2.tc_interval
Cannot find data for entry: 'olsrv2.tc_interval'.
Command returned an error
```

```
> config get interface.hello_interval
Cannot find data for entry: 'interface.hello_interval'.
Command returned an error
```

Is this behaviour correct? is possible to return the default value of that key?

**Comment by gabri94** [comment]
It would be easier to have a single command for both things, but I can check the configuration before, and if it's empty I can assume that the value has not been modified by the user and thus query the default one.

**Comment by HRogge** [comment]
I finally pushed a change that implements a "config query" command for the
remotecontrol plugin.

This should solve your issue.

**Comment by mathiashro** [comment]
@gabri94, I guess we are good to move on closing this case?
