### ISSUE TITLE
UDP socket issue

### ISSUE THREAD

**Issue by gwaeber** [OLSR/OONF#14]
We saw that sometime (randomly) OLSRd2 has a problem (OLSRd2 is running but not working) at launch, cf. error message below:

> 16:02:58.623 WARN(packet_socket) src-plugins/subsystems/oonf_packet_socket.c 241: Cannot send UDP packet to 224.0.0.109:269: Bad file descriptor (9)

This error persist until the instance of OLSRd2 is killed. If we relaunch OLSRd2 with the same configuration, the problem can reappear or not, seems random.
Last version (commit 3a2dd24) of OLSRd2 was used, this issue also appears in previous versions.

**Comment by HRogge** [comment]
Hmm...

could you try the following patch? (only compile-tested)

Henning
On Thu, Apr 19, 2018 at 8:17 AM Gilles Waeber <notifications@github.com>
wrote:

> We are using a several Ubuntu 14.04.5 LTS (3.13.0-144) machines on a
VMware cluster.

**Comment by HRogge** [comment]
I tried to attach a file to the mail, maybe github removed it... let me see
that I publish it on github in a branch.

Henning

**Comment by HRogge** [comment]
Pushed it to the packet_socket_bug branch.

Henning

**Comment by gwaeber** [comment]
With the patch, the issue appears less often but we still have it from time to time. I'll come back to you when we have something more concrete.
