### ISSUE TITLE
DAT metric always remains the same

### ISSUE THREAD

**Issue by gwaeber** [OLSR/OONF#15]
We noticed that the FF DAT plugin always returns the same 1.02 kbit/s value for the DAT metric. In the OLSRd2 log file we have the following information:
```
23:31:53.789 INFO(ff_dat_metric) src-plugins/nhdp/ff_dat_metric/ff_dat_metric.c 636: Datarate for link 10.100.0.2 (eth0) not available
23:31:53.790 DEBUG(ff_dat_metric) src-plugins/nhdp/ff_dat_metric/ff_dat_metric.c 714: Query incoming linkspeed for link 10.100.0.2: 1024
```
After digging in the code, we found out that the `get_scaled_rx_linkspeed()` method from ff_dat_metric.c always returns "1". Therefore the incomming linkspeed from the log file always equals to _scaled_speed * DATFF_LINKSPEED_MINIMUM_ with _scaled_speed_ = 1 and DATFF_LINKSPEED_MINIMUM = 1024.

The method `get_scaled_rx_linkspeed()` stops and returns "1" because the _raw_rx_rate_ (obtained from `get_raw_rx_linkspeed()`) always equals to "-1".

Do you have a "working" DAT metric on your side ? Are we missing something in the OLSRd2 configuration ?

OLSRd2_static was tested on several Ubuntu 14.04.5 LTS (3.13.0-144) virtual machines as well as on different HP laptops running Ubuntu 14.04 or 16.04 connected through Ethernet cable.

**Comment by gwaeber** [comment]
Okay.
In our case, the DAT plugin always returns a default fixed speed resulting in a constant DAT metric. What we do not understand is why are all the links speed not known, Do we miss something ?

**Comment by gwaeber** [comment]
What is weird is that we have a fixed value, but we do not receive a fixed Ethernet link-speed but a default value.
When the `get_raw_rx_linkspeed()` function is querying the layer2 database, we always receive "-1", the l2 db seems to be empty.

**Comment by HRogge** [comment]
The eth_listener is not part of the default olsrd2 executable.

People complained that the value extracted from the local ethernet card
might be wrong because of a switch in between.

Henning Rogge

**Comment by gwaeber** [comment]
We tested both eth_listener and nl80211_listener plugins on two laptops. This is our configuration file:

```
[global]
      fork false
[interface=wlan0]
      hello_interval 1.0
      hello_validity 10.0
[http]
      acl default_accept
      port 2006
```

We never managed to get a correct bitrate, therefore the DAT metric nevers exceed 1024 bit/s.
Do we miss something in the configuration file in order for the plugins (eth, nl80211, dlep, ...) to get the bitrate ?
Thank's for your time

**Comment by gwaeber** [comment]
Output of the `iw wlan0 station dump` command:
- [wlan0.txt](https://github.com/OLSR/OONF/files/1963422/wlan0.txt)
- [wlo1.txt](https://github.com/OLSR/OONF/files/1963423/wlo1.txt)

**Comment by gwaeber** [comment]
I can confirm that the executable really contains the nl80211_listerner. When querying the layer2info about neighbours, we don't have information about them.
Outputs (layer2info neighbor, ifconfig and olsrd2_static -v) on the two laptops:
- [lap01.txt](https://github.com/OLSR/OONF/files/1966686/lap01.txt)
- [lap08.txt](https://github.com/OLSR/OONF/files/1966687/lap08.txt)

**Comment by HRogge** [comment]
As far as I can see the layer2 "neighbor" database gets populated with
data... the two wifis see each other as neighbors.

Lets have a look into the link database of NHDP next.

can you send me the output of

echo /nhdpinfo json link | nc 127.0.0.1 2009

Henning

**Comment by Takepr** [comment]
Dear HRogge, 

here are the outputs of  

`echo /nhdpinfo json link | nc 127.0.0.1 2009`

on the two laptops

[lap01_2.txt](https://github.com/OLSR/OONF/files/1966897/lap01_2.txt)
[lap08_2.txt](https://github.com/OLSR/OONF/files/1966898/lap08_2.txt)

Thank you.

**Comment by HRogge** [comment]
Hmm...

So one bug is fixed but not "the other one"...

Just a question, who is the third participant in the wifi, the one with MAC
"e8:37:7a:a4:dc:00" ? Because I see a linkspeed to with this neighbor, but
not between the two mesh-nodes.

could you try to send a ping between the two mesh nodes to make sure its
not an issue with "unicast probing" (another plugin in OONF)?

Henning

**Comment by Takepr** [comment]
About the

>  one bug is fixed but not "the other one"...

If you are referring to the DAT of 1,02 kbit/s, we have always obtained a value <= to 1,02 kbit/s. But the logs show that the datarate is not available.

e8:37:7a:a4:dc:00 is an wifi router connecting the two laptops.

We are also doing some tests with virtual machines with the same results.

Example of output obtained from the second node of an 4 nodes inline topology

node-1 <=> node-2 <=> node-3 <=> node-4

take@node-2:~$ echo /layer2info neighbor | nc 127.0.0.1 2009
emane0	2	02:02:00:00:00:02	02:02:00:00:00:01		0		0mdBm	0mdBm	0bit/s	0bit/s	0bit/s	0bit/s	0byte	0byte	0	0	0bit/s	0bit/s	0	0	0	0	0	0	0bit/s	-7	0us	0	0	0										ffdat bc loss				
emane0	2	02:02:00:00:00:02	02:02:00:00:00:03		0		0mdBm	0mdBm	0bit/s	0bit/s	0bit/s	0bit/s	0byte	0byte	0	0	0bit/s	0bit/s	0	0	0	0	0	0	0bit/s	-7	0us	0	0	0										ffdat bc loss

**Comment by HRogge** [comment]
On Wed, May 2, 2018 at 2:51 PM Takepr <notifications@github.com> wrote:

> About the

> one bug is fixed but not "the other one"...

> If you are referring to the DAT of 1,02 kbit/s, we have always obtained a
value <= to 1,02 kbit/s. But the logs show that the datarate is not
available.

> e8:37:7a:a4:dc:00 is an wifi router connecting the two laptops.

Okay, that explains the problem.

The wifi stack can only determine link speed to direct neighbors... if you
place two Wifi-Clients on the same AP (and bridge them through the AP),
they have no link-speed between each other.

> We are also doing some tests with virtual machines with the same results.

> Example of output obtained from the second node of an 4 nodes inline
topology

> node-1 <=> node-2 <=> node-3 <=> node-4

> take@node-2:~$ echo /layer2info neighbor | nc 127.0.0.1 2009
> emane0 2 02:02:00:00:00:02 02:02:00:00:00:01 0 0mdBm 0mdBm 0bit/s 0bit/s
0bit/s 0bit/s 0byte 0byte 0 0 0bit/s 0bit/s 0 0 0 0 0 0 0bit/s -7 0us 0 0 0
ffdat bc loss
> emane0 2 02:02:00:00:00:02 02:02:00:00:00:03 0 0mdBm 0mdBm 0bit/s 0bit/s
0bit/s 0bit/s 0byte 0byte 0 0 0bit/s 0bit/s 0 0 0 0 0 0 0bit/s -7 0us 0 0 0
ffdat bc loss

You could use (with the fix I pushed) the following configuration to add a
"receiving link speed" as a configuration parameter (relative to neighbor
02:02:00:00:00:01)

[interface=emane0]
         l2neigh            rx_bitrate 10M  02:02:00:00:00:01

**Comment by Takepr** [comment]
We are trying to connect the laptops without an intermediate router.

About the virtual machines (which are directly connected) .

With the configuration on node-2 :

```
[interface=emane0]
      hello_interval 1.0
      hello_validity 10.0
      l2neigh            rx_bitrate 10M  02:02:00:00:00:01
```

```
take@node-2:~$ echo /layer2info neighbor | nc 127.0.0.1 2009
emane0	2	02:02:00:00:00:02	02:02:00:00:00:01		0		0mdBm	0mdBm	0bit/s	0bit/s	0bit/s	0bit/s	0byte	0byte	0	0	0bit/s	0bit/s	0	0	0	0	0	0	0bit/s	-7	0us	0	0	0										ffdat bc loss		
emane0	2	02:02:00:00:00:02	02:02:00:00:00:03		0		0mdBm	0mdBm	0bit/s	0bit/s	0bit/s	0bit/s	0byte	0byte	0	0	0bit/s	0bit/s	0	0	0	0	0	0	0bit/s	-7	0us	0	0	0										ffdat bc loss		
```	

In the logs :
```
15:03:51.778 INFO(ff_dat_metric) src-plugins/nhdp/ff_dat_metric/ff_dat_metric.c 665: Datarate for link 10.100.0.1 (emane0) not available
15:03:51.779 INFO(ff_dat_metric) src-plugins/nhdp/ff_dat_metric/ff_dat_metric.c 665: Datarate for link fe80::2:ff:fe00:1 (emane0) not available
```

**Comment by Takepr** [comment]
Hello,

as you may have noticed we are trying to use OLSRd2 with EMANE nodes.

Can the problem be that the NL80211 listener is not able to retrieve anything from the Linux MAC80211 subsystem (Because of EMANE virtual interfaces) and therefore no data is populating the layer2 database ?

Thank you

**Comment by HRogge** [comment]
[interface=emane0]
         l2neighbor            rx_bitrate 10M  02:02:00:00:00:01

(I really have to get that parser to throw an error by default if someone
sets an unknown parameter *sigh*)

Henning

**Comment by HRogge** [comment]
On Wed, May 2, 2018 at 5:25 PM Takepr <notifications@github.com> wrote:

> [interface=emane0]
>          l2neighbor            rx_bitrate 10M  02:02:00:00:00:01
>
> "domain_metric":"ff_dat_metric",
> "domain_metric_in":"10.034Mbit/s",
> "domain_metric_in_raw":214,
> "domain_metric_out":"943bit/s",
> "domain_metric_out_raw":2277120,
>
>
> This parameter is working thank you.
>
Great to hear that.

> Do you know if the FF DAT metric can obtain a "live" datarate with EMANE
> (without fixing it in the configuration file) ?
>
Does EMane has some kind of API/Socket to query the simulated link speed?
If yes a special "listener" plugin (similar to the nl80211_listener) could
do the job.

The problem is that EMane (of course) does not simulate its interfaces
through the Linux Wifi stack, so the OONF just sees a raw interface (not
even an ethernet).

Henning
Henning
