### ISSUE TITLE
OLSR not updating routing table after route deletion

### ISSUE THREAD

**Issue by gwaeber** [OLSR/OONF#16]
Hi,

We observed that, if we manually delete an OLSR route (`route del` command), OLSRd2 is not adding it again in the routing table. It seems that OLSRd2 is kind of "freezed".
OLSRd2_static was tested on a Ubuntu 14.04.5 LTS (3.13.0-144) virtual machine.

Best regards

**Comment by HRogge** [comment]
If you would like to discuss this as a feature request, come over to the
olsr-dev list where other people can also participate.

I think you are the first one who even asks about this feature.

**Comment by gwaeber** [comment]
Thank's for the quick answer !

Best regards
Gilles
