### ISSUE TITLE
http.acl not considered?

### ISSUE THREAD

**Issue by pocki80** [OLSR/OONF#18]
I was trying to restrict the access list for the http plugin to a certain IP range. In fact it looks like the parameters frim http.acl are not considered at all.

Relevant part of my config:

[telnet]
port 2009
[http]
bindto 0.0.0.0
bindto ::0
port 8000
acl default_reject
acl *myIpAddress*

But, still the request http://*publicIp*:8000/telnet/olsrv2info%20originator is available from anywhere.

**Comment by HRogge** [comment]
Hi,

I have to look how the telnet/http bridge has been implemented... might be
that the telnet ACL is the relevant here, which would not be what you (as a
user) should expect.

the http acl should work for all HTTP access.

Henning

**Comment by HRogge** [comment]
Hi,

can you try the following patch?

```
diff --git a/src/base/oonf_stream_socket.c b/src/base/oonf_stream_socket.c
index 716c1f25..ca08fe4e 100644
--- a/src/base/oonf_stream_socket.c
+++ b/src/base/oonf_stream_socket.c
@@ -344,6 +344,9 @@ oonf_stream_add_managed(struct oonf_stream_managed *managed) {
   if (managed->config.session_timeout == 0) {
     managed->config.session_timeout = 120000;
   }
+  if (managed->config.acl == NULL) {
+    managed->config.acl = &managed->_managed_config.acl;
+  }
 
   managed->_if_listener.if_changed = _cb_interface_listener;
   managed->_if_listener.name = managed->_managed_config.interface;

```

**Comment by pocki80** [comment]
Looks like this patch fixes that issue. 
Thx! Please merge it

**Comment by HRogge** [comment]
Change commited and pushed to develop branch.
