### ISSUE TITLE
systeminfo-time showing strangly high values

### ISSUE THREAD

**Issue by pocki80** [OLSR/OONF#20]
using telnet plugin "systeminfo time" I see that the uptime second counter increases in an unexpected fast was. As there war "seconds since deamon start" in former versions, I looks like this right now:

```
time_system     time_internal
17:15:58.331	 2.628k (a few seconds after daemon start)
17:16:11.643	 7.065k (13.312sec later, increased by 4.437k that is 0.3333k per second)
17:16:21.668	10.407k
17:16:52.832	20.795k
17:19:47.271    78.941k
```

**Comment by HRogge** [comment]
Hi,

we had a fix about this in v0.15.1-100-ga1a4c7e4, can you test the most
recent "develop" branch?

Henning

**Comment by pocki80** [comment]
Actually no, I was not able to test it until now. But looking at the code changes it seems to be fixed. 
Though, waiting for all these recent commits to get merged to master. 
BR

**Comment by HRogge** [comment]
Sorry,

I have been tracking a problem in the main netlink code for weeks... I
don't want to merge before this is done because it tends to break the
routing agent in my special test setup... I am lucky I found a way to
trigger it reliable.
