### ISSUE TITLE
ff_dat_metric plugin configuration

### ISSUE THREAD

**Issue by gwaeber** [OLSR/OONF#24]
When including configuration for the _ff_dat_metric_ plugin in our OONF configuration file, we get the following error:

> 14:04:09.096 WARN(config) src/libcore/oonf_cfg.c 368: Configuration validation failed: Cannot find schema for section type 'ff_dat_metric'

How can we configure the _ff_dat_metric_ plugin correctly ?

OONF was started with the command: 

> sudo olsrd2_static --load routing1.conf

The routing1.conf file:

> [global]
>     fork true
>     lockfile /home/take/predicTAKE/cluster/experiments/9n_9_TDMA_square_dat/persist/1/run/olsrd2.lock
> 
> [log]
>     syslog false
>     stderr true
>     file /home/take/predicTAKE/cluster/experiments/9n_9_TDMA_square_dat/persist/1/log/olsrd2.log
> 
> [olsrv2]
>     originator -127.0.0.1/8
>     originator -::/0
>     originator default_accept
>     tc_interval 8.0
>     tc_validity 80.0
> 
> [interface=emane0]
>     bindto -127.0.0.1/8
>     bindto -::/0
>     bindto default_accept
>     hello_interval 2.0
>     hello_validity 20.0
> 
> [http]
>     acl default_accept
>     bindto 10.99.0.1
>     port 2006
> 
> [telnet]
>     acl default_accept
>     bindto 10.99.0.1
>     port 2009
> 
> [ff_dat_metric]
>     interval 1.0
>     squared_loss true

**Comment by HRogge** [comment]
Please use the "--schema" option to determine the correct names of configuration options.

Most of the ff_dat_metric options are in the "interface" section (see with "olsrd2 --schema=interface") to be able to set them by interface.

**Comment by gwaeber** [comment]
Thank's for the information, I will have a look at it.

**Comment by giannisfourfouris** [comment]
Hello,

Did you finally manage to configure the ff_dat_metric through the interface section? 
I tried to do the same but there are a few attributes about the ff_dat_metric .
I am particularly interested in 'interval' and 'window' attributes which are not in the 'interface' section
but http://www.olsr.org/mediawiki/index.php/FF_DAT_Metric_Plugin introduces them.
Is there finally a way to alter those attributes?

Thank's in advance!

**Comment by HRogge** [comment]
I don't see these Parameters in the current codebase, maybe they got removed some time ago. The wiki is just horrible outdated.

please check with the command line parameter "--schema=interface" for all available parameters known to the code.
