### ISSUE TITLE
Cross-Compiling for Raspberry Pi

### ISSUE THREAD

**Issue by mikysal78** [OLSR/OONF#27]
How-to for Cross-Compiling and generate deb file for rasbian?
Thanks.

**Comment by HRogge** [comment]
These two problems are independent to each other...

first you need to create a cmake build-directory linked to a cross-compilation toolchain. See the /cmake/cross directory for some (outdated?) examples.

then you need to generate your debian package, you can try the files/create_debian_package.sh script... but it is also quite old.

**Comment by HRogge** [comment]
Can I close this issue?

**Comment by mikysal78** [comment]
I have not solved but I close.
thanks.
