### ISSUE TITLE
Build failing due to DNS library with GCC >9.0

### ISSUE THREAD

**Issue by aJunk** [OLSR/OONF#30]
When compiling with GCC 10 `dns_rr_i_init()` in _include/oonf/generic/dns_query/dns.h:527_ throws "lvalue required as unary '&' operand".

Apparently this code working was a bug as it should have been an r-value (see [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=88766) and [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88773)).

There was a workaroung for GCC > 9.0 in another project [here](https://github.com/wahern/cqueues/issues/212). However, I just (very quickly) tried doing the same for version 10 which did not work.

The same issue cropped up in several projects I found including GnuPG. They seem to have fixed it for them. Maybe their solution can be used here as well. ([link to the official repo](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blobdiff;f=dirmngr/dns.h;h=49b1c78bbf6e7abededb37696e16aeac04a93cf0;hp=da450c611b0075c600ed0e6270f28a322ce793ff;hb=6501e59d3685bb58753c9caea729a4b0eca3942a;hpb=a1ccfe2b37847cce0db2fb94a7365c9fa501eda4), [history in github mirror](https://github.com/gpg/gnupg/commits/master/dirmngr/dns.h))

**Comment by PolynomialDivision** [comment]
which branch? we deploy some patchset for olsrd2 in the openwrt-routing feed.

**Comment by fredleb** [comment]
Same here when trying to compile the "develop" branch:

```
In file included from /home/jenkins/dev/OONF/src/generic/dns_query/dns.c:89:
/home/jenkins/dev/OONF/src/generic/dns_query/dns.c: In function 'dns_ai_nextent':
/home/jenkins/dev/OONF/include/oonf/generic/dns_query/dns.h:527:16: error: lvalue required as unary '&' operand
  527 |  dns_rr_i_init(&dns_quietinit((struct dns_rr_i){ 0, __VA_ARGS__ }), (P))
```

**Comment by aJunk** [comment]
I am sorry for the late reply, I did not see the message.

> which branch? we deploy some patchset for olsrd2 in the openwrt-routing feed.
The develop branch was the one i tried it with. I added a couple of "extern"s to some declaration (see pull request) and then I notices the problem I described above.

**Comment by mathiashro** [comment]
Hello @aJunk, are we good to move on closing the case? There were also some recent compile error resolutions, may be your issue is now solved.

**Comment by mathiashro** [comment]
Compiling currently without any errors.
