### ISSUE TITLE
Per-interface tc_* parameters ignored

### ISSUE THREAD

**Issue by fredleb** [OLSR/OONF#37]
It is possible to define per-interface hello_* parameters, which comes in handy for very slow interfaces. Is it possible for tc_* parameters ?

**Comment by HRogge** [comment]
Unfortunately no... Hellos only travel a single hop, so each router controls the outgoing rate on each interface.

But TCs are flooded through the network, so the outgoing rate depends on the size of the network and the configuration of all routers.

**Comment by fredleb** [comment]
Could the tc flooding be delayed until a timer is reached and/or newly arriving tc packet consolidated before being propagated ?

**Comment by HRogge** [comment]
You will have to test this out for your scenario...
