### ISSUE TITLE
Status of crypto plugins

### ISSUE THREAD

**Issue by svasilaras** [OLSR/OONF#39]
What is the status of the crypto plugins? I've tried to re-build the code and include the simple-security plugin but found out that all crypto plugins .h files are missing from the latest distribution, while the .c files are there but seem to be outdated.
What is the reason for this? Was it that no one was interested in updating the code or that the code never worked properly in the first place and thus a decision was made to stop maintaining it? Is there a plan to fix this in the near future?

**Comment by HRogge** [comment]
the (crypto-)code is not complete and nobody is maintaining it.
the same (in terms of maintaining) is true for the rest of OONF... at some point it got too much to handle for a single person show.

I am/have-been using the code myself mostly for research, which means that C as a language is a horrible choice.

**Comment by svasilaras** [comment]
Your answer makes sense. Actually, I have tried to build the code by copying and pasting the .h files from the Doxygen pages of olsr.org. After a lot of editing to fix all the compilation errors, I managed to get the plugins initializing and starting (according to the generated log file). However, there are no relevant TLVs (of type 5 or 6) found in the generated HELLO and TC messages. So I assumed that either the crypto-code has never worked properly or that I have not been able to update it appropriately (my code editing was driven by the compilation errors without a good understanding of how the code works).

**Comment by HRogge** [comment]
As you most likely know, the code is meant to work as with the "post-processing" callbacks the RFC5444 code has, so it can add the necessary security-TLVs in a transparent way. I think I got parts of the code working at some time, but the rest was difficult to finish so I most likely deactivated the existing code until it can be fixed.

One issue at that time was the lack of a good and documented crypto-library on OpenWRT... yes, OpenSSL library is a mess, but at least its present on every linux desktop and server system and its documented. OpenWRT has some crypto library (tomcrypt at that time?), but it lacks a good documentation.

Of course the question is why would you need a signature algorithm for OLSR anyways... in my opinion it would be better to work on a good way to add a transparent linklayer security for the radios... keeping both user traffic and control traffic save.

**Comment by mathiashro** [comment]
Closing for the moment (stale).
