### ISSUE TITLE
L2 Generator never updates the data

### ISSUE THREAD

**Issue by jpo-github-work** [OLSR/OONF#44]
@HRogge As I understand it, the test in line [L204](https://github.com/OLSR/OONF/blob/1bd73550a42686d47f487a9c5d5602304a8712c7/src/generic/layer2_generator/layer2_generator.c#L204) prevents the plugin from ever updating the L2 data. Can someone who understands the intend here take a look?

I think this line should be (note the **!**):
`  if (!oonf_layer2_origin_is_added(&_origin)) {`

**Comment by mathiashro** [comment]
PR has been merged.
