### ISSUE TITLE
olsrd2 segfaults when doing ``layer2info json neighbor``

### ISSUE THREAD

**Issue by aaronkaplan** [OLSR/OONF#5]
How to repeat:

```
nc localhost 2009
<ENTER>
layer2info json neighbor

```
-> instant crash

**Comment by HRogge** [comment]
Okay Aaron, you should know how to produce a better bug report.

Which version of olsrd2 (git commit), which platform?

**Comment by aaronkaplan** [comment]
> On 23 Nov 2016, at 13:24, Henning Rogge <notifications@github.com> wrote:
> 
> Okay Aaron, you should know how to produce a better bug report.
> 
> Which version of olsrd2 (git commit), which platform?

Latest obviously :)
x86, 64 bit

As discussed.

**Comment by HRogge** [comment]
Can you produce a backtrace (with line-numbers!)?
