### ISSUE TITLE
error in the Cmake ..

### ISSUE THREAD

**Issue by abdulahadkawaf** [OLSR/OONF#59]
I'm using ubuntu on rasp 4 and this error shows when i do the cmake in the build directory

CMake Error at cmake/get_version.cmake:50 (string):
  string sub-command SUBSTRING requires four arguments.
Call Stack (most recent call first):
  CMakeListsGlobal.cmake:50 (include)
  CMakeLists.txt:14 (include)

Git commit: , Git version: 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
--     Optional plugin nl80211_listener is not available for executable dlep_radio
--     Optional plugin nl80211_listener is not available for executable olsrd2
--     Optional plugin cfg_uciloader is not available for executable olsrd2
--     Optional plugin nl80211_listener is not available for executable olsrd2_dlep
-- Configuring incomplete, errors occurred!

**Comment by mathiashro** [comment]
Compiling is currently working fine.
