### ISSUE TITLE
Olsrd 2 kill itself

### ISSUE THREAD

**Issue by AbhishekUoR** [OLSR/OONF#6]
I am using Mininet emulator wherein there are stations in multiple LAN AND I want to route 2 stations which are in different LAN.I am able to do that using olsrd2_static when I "xterm" to that station.But when I try to write same command within the script ,the olsrd2_static works fine bute after sometime it stops.

**Comment by HRogge** [comment]
Do you get a segfault? Did you try to get a stacktrace with gdb?

**Comment by mathiashro** [comment]
Issue closed due to missing feedback or further results.
