### ISSUE TITLE
Compile Error (Ubuntu 22.04)

### ISSUE THREAD

**Issue by KyleKotowick** [OLSR/OONF#60]
Getting a compilation error on Ubuntu 22.04.

```
sudo apt install cmake build-essential pkg-config libnl-3-dev libtomcrypt-dev
git clone https://github.com/OLSR/OONF.git
cd OONF/
git checkout v0.15.1
cd build/
cmake ..
make
```

Everything works until `make`, which outputs:
> /usr/bin/ld: CMakeFiles/oonf_dlep_radio.dir/radio/dlep_radio_interface.c.o:/home/kyle/OONF/src-plugins/generic/dlep/radio/dlep_radio_internal.h:52: multiple definition of 'LOG_DLEP_RADIO'; CMakeFiles/oonf_dlep_radio.dir/radio/dlep_radio.c.o:/home/kyle/OONF/src-plugins/generic/dlep/radio/dlep_radio_internal.h:52: first defined here
/usr/bin/ld: CMakeFiles/oonf_dlep_radio.dir/radio/dlep_radio_session.c.o:/home/kyle/OONF/src-plugins/generic/dlep/radio/dlep_radio_internal.h:52: multiple definition of 'LOG_DLEP_RADIO'; CMakeFiles/oonf_dlep_radio.dir/radio/dlep_radio.c.o:/home/kyle/OONF/src-plugins/generic/dlep/radio/dlep_radio_internal.h:52: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [src-plugins/generic/dlep/CMakeFiles/oonf_dlep_radio.dir/build.make:324: liboonf_dlep_radio.so.0.15.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:1798: src-plugins/generic/dlep/CMakeFiles/oonf_dlep_radio.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by KyleKotowick** [comment]
It works if you checkout `master` instead of the most recent tag. A new tag should be published with these fixes.

**Comment by mathiashro** [comment]
Yes, we will try a release soon. Closing here.
