### ISSUE TITLE
lan_import plugin build on develop branch

### ISSUE THREAD

**Issue by XDjackieXD** [OLSR/OONF#61]
The simple fix for this was only merged to master, not to develop (https://github.com/OLSR/OONF/commit/c7d404f8e9682f008fe6f11d7912ccfc8fb4aad3).
Please cherry-pick this from master to develop!

**Comment by mathiashro** [comment]
Hi @XDjackieXD , do you mind adding another PR for the develop-branch? (For the sake of complexity we aim to move all changes from dev to master soon, as there is no active development at the moment.)

**Comment by XDjackieXD** [comment]
https://github.com/OLSR/OONF/pull/62 already done ^^
