### ISSUE TITLE
OLSv2 Multicast Group Recalculation

### ISSUE THREAD

**Issue by giannisfourfouris** [OLSR/OONF#63]
When running OLSRv2 in a CORE/EMANE emulator, I noticed an issue related to the multicast group behavior. By default, when the protocol starts operating, it creates a multicast group with the IP address '224.0.0.109'. However, I observed that when I set the routing willingness of all routers to the maximum value (15, denoting "will always"), the protocol attempts to recalculate the multicast group and deletes the initial one. This results in a loss of network communications.

According to RFC 7181, it states that "In a MANET in which all routers have WILL_ROUTING = WILL_ALWAYS, topology reduction will effectively be disabled, and all routers will advertise all their links in TC messages." Based on this information, my understanding is that the multicast group should remain unchanged, and the routing MPR (Multipoint Relay) nodes should be disabled, causing the size of TC (Topology Control) messages to increase as all routers now include information about all their links.

However, I'm unsure if I have misunderstood something. Should the multicast group be recalculated when all routers have the maximum routing willingness? Is there a possibility that this issue could be attributed to a bug?  Any insights or clarifications would be greatly appreciated.

Thank you in advance for any assistance or clarification provided.

**Comment by mathiashro** [comment]
Currently there is no active development here, since you are missing a response for quite some time - I'm closing the case for now. If you can provide a solution yourself, kindly update here as well. Thank you.
