### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by fpoltronieri** [OLSR/OONF#66]
Hi everyone,

When compiling on my x86_64 Arch Linux laptop (Kernel 6.5.8-arch1-1) I have the following error:

`/home/filippo/code/mininet-wifi-compiled/OONF/src/librfc5444/rfc5444_reader.c:134:1: error: conflicting types for ‘rfc5444_reader_handle_packet’ due to enum/integer mismatch; have ‘enum rfc5444_result(struct rfc5444_reader *, const uint8_t *, size_t)’ {aka ‘enum rfc5444_result(struct rfc5444_reader *, const unsigned char *, long unsigned int)’} [-Werror=enum-int-mismatch]
  134 | rfc5444_reader_handle_packet(struct rfc5444_reader *parser, const uint8_t *buffer, size_t length)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

I am using GCC 13.2.1.

Does anyone have any hints on how to solve this compilation error?

**Comment by mathiashro** [comment]
@fpoltronieri , do you mind re-checking the issue and report here if it still persists? I compiled yesterday the master branch without any issues (on aarch64).
